language: node_js
node_js:
- 12.13.1
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: V8888diNqgnJP0M0tJvF+JZcAl9IWDNjEK1r6ALBOe9RDJpw5XKXG2Pi1IULI1eUBAxlOZUJzNO07XYFqbhPR3HBrHSux6wR8NllBQY3u4Vy5FjSSPTZWYlCE8Bj/QrXzsgPikQHptrdSh8YQHcITDXpzrBu3NoFrrVJjfz65GmAjV6ZQf0GdBuiW+9BysZd9q5vGGXrhtHPUpYnoeEfLsmxA8bPRNddQZjIqItVZorcxVDZQ/wDrbmfdT9fMjn7c+o1RzuJiXtbRPaOKI0+6qILpfZTqwJuFU1pQzqBwA3n3TQfNCtHctqX3pW+J8LkVHuGwLo/LAt8ThfuWYyRLBrXFM/19WGhgjcPNxmBbAZEhCoAGyoJ/iIrcHtEylLA4CqxhH6YOubfLKx/Qg+aHj2+/SZWPum84lmVh3YzPXPtjXB0b0QEqnK/uFZXtjWcKzMfFqetkaQM4zHVhsibNnVN69wJBr08n+iNvX3BDkJ4iZNdUz/gIUYVPyeC493Nbt5EDfWG6bvRclWDPPgKBz2c2mZrAL8BN3tH3mbwDrsqsHk6BqSKZ7g53aodYgTMzWADGtvCik3atYwQU0ufJQ2Sgla/77hdiWbn+EtlpCe9eDYWISmhxguMyza8jXpSaAuLluMu4k8HbOvehaH8K/CbJv+MRLuH2pVm16QHCW0=
